version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "No2zCBBWBEgBBH5A8xNd"
      MYSQL_DATABASE: "api_alares_backend"
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - api-network
  # app:
  #   image: murillo9mm/server-php-8:1.0
  #   container_name: apache
  #   volumes:
  #   - ./:/var/www/html
  #   ports:
  #   - 8010:80
  #   # links:
  #   # - mysql
  #   # depends_on:
  #   # - mysql
  #   tty: true
  #   networks:
  #     - api-network
  # db:
  #   image: mongo
  #   container_name: mongo    
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./mongodata:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: KAIiXZxtq1KZKEKX
  #   networks:
  #         - api-network

networks: 
  api-network:
    driver: bridge

## mongosh mongodb://root:KAIiXZxtq1KZKEKX@localhost:27017 --username root --authenticationDatabase admin